[package]
name = "regexp_extract_datafusion"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "49.0.0"
arrow = "56.0.0"
regex = "1.10"
tokio = { version = "1.0", features = ["rt-multi-thread"] }

[dev-dependencies]
tokio-test = "0.4"
